### ISSUE TITLE
Bug: Coupon get applied even if invalid

### ISSUE THREAD

**Issue by Zelig880** [tastyigniter/ti-ext-coupons#15]
**Expected behavior:**
As an user I expect the coupon that get automatically applied to the cart, to be valid for my order

**Actual behavior:**
Coupon that are automatically applied do not take into consideration the "days" in which the coupon are valid, and therefore can be applied, but invalid (an error popup will come up as soon as they are applied).

**Reproduce steps:**
- Create a coupon with recurrence on a different day that today
- Make the coupon auto applicable
- Go on the website
- Add something to the cart that will make the coupon applicable
- see the coupon being applied even if it should not (as it is the wrong day of the week)

**Version:**
3.4.4-beta-26

**Additional Information:**
I have not personally checked if all other settings (minimum price, correct items, etc..) work properly.

**Comment by ryanmitchell** [comment]
Thanks for the reminder - this has been on my list to circle back to.
I've opened a PR with a fix
