### ISSUE TITLE
Minimum total Validation when limit to categories / menu items

### ISSUE THREAD

**Issue by yoursantu** [tastyigniter/ti-ext-coupons#17]
**Expected behavior:**
Minimum Total validation when coupons limit to categories / menu items

**Actual behavior:**
When Coupons limit to Categories / Menu items and Minimum Total is set, it does not validated, the coupon discount applied before Minimum Total reached.
ie:  I have 2 items that is selected on coupons extension.
Item 1 price 100
Item 2 price 200
have set 10% discount on minimum total to 200
but when i add Item 1 to cart, the coupon discount also applied before minimum total is reached!!
(Refer Image below)

**Version:**
3.0.4-Beta.27

**Extension Version:**
Coupons 1.4.0

![Coupons-Condition](https://user-images.githubusercontent.com/14079339/107610962-e50a7b00-6c68-11eb-9b2a-e4e9596d0d19.png)

**Comment by Zelig880** [comment]
Hi.. Have you tried to click checkout? 

There is an existing bugs ( that I was going to work on now) that even if a coupon is invalid and get removed from the cart, it still actually show in the side bar. 

Usually if you click the Checkout the total of the card should be 100 in your case.

**Comment by sampoyigi** [comment]
This issue looks fixed. Closing, but please reopen if it still occurs.
