### ISSUE TITLE
Limiting max uses per customer doesn't work and global limit doesn't update

### ISSUE THREAD

**Issue by pablogfb** [tastyigniter/ti-ext-coupons#29]
**Expected behavior:**
Introducing a max uses limit per customer should limit the maximum uses per customer. Also changing global limit field should change the maximum uses limit

**Actual behavior:**
Changing max uses limit per customer and max uses in general does not affect to the behavior

**Reproduce steps:**
Go to admin > Marketing > Coupon > Edit one coupon
Set limits once. Make some orders using that coupon. Change those limits. Continue making orders using that coupon

**Version:**
3.0.4

**Comment by ryanmitchell** [comment]
This again works fine in my environment, can you provide full and complete details for testing, including your coupon settings and steps you went through.

**Comment by pablogfb** [comment]
I have done it again:

1. Create a new coupon. Percentaje (10%), Allways apply. Limit once per customer
2. You can place several orders and the coupon will be always applied. 
 
If you edit the coupon and save it again then it works fine. Maybe it isn't saving all fields on creation

**Comment by sampoyigi** [comment]
Fixed
