### ISSUE TITLE
Automatic apply coupon code

### ISSUE THREAD

**Issue by iTzMeRafa** [tastyigniter/ti-ext-coupons#3]
**Expected behavior:**
After adding something to the cart, the system should also check if the customer is eligable for a coupon (by condition).

**Actual behavior:**
The only way is to manually apply codes

**Reproduce steps:**
Well, there is currently not the option for this

**Version:**
3.0.4-beta.23.2

**Additional Information:**
I think a simple solution would be to apply all coupon codes available in the system when a new item is added to the cart.
In which file would you do this?

**Comment by sampoyigi** [comment]
Hehe, just discovered the transfer issue feature. Cool stuff.

**Comment by ryanmitchell** [comment]
Cool that’s handy. 

Yep I’m happy to work on it - feels like something we could use too. 

Slightly off topic but can you only add one coupon to the cart at a time? I hadn’t noticed that limitation until I started thinking about this.

**Comment by sampoyigi** [comment]
Cool stuff!

Yea just one per order. It crossed my mind when I was working on the cart item condition bit and its probably possible to allow more than one per order with little modifications to the coupon cart condition class.

**Comment by ryanmitchell** [comment]
It would be great to support multiple coupons - I had kind of assumed it did without ever really checking. What changes are needed to the coupon condition?

**Comment by ryanmitchell** [comment]
Created a branch with the initial apply automatically work:
https://github.com/tastyigniter/ti-ext-coupons/tree/apply-automatically

**Comment by sampoyigi** [comment]
Cool cool, will have a look.

**Comment by BreakSecurity** [comment]
This can be closed
