### ISSUE TITLE
UI glitch showing transparent dropdown menu

### ISSUE THREAD

**Issue by BreakSecurity** [tastyigniter/ti-ext-coupons#5]
**Expected Behaviour:**
in the section to set up coupons, the windows should be displayed correctly.

**Actual behaviour:**
the window to select which category to assign the coupons to is transparent as shown in the image.

**Reproduce steps:**
Go to the "coupons" section, create a new coupon, set which categories the coupon is valid for.

**Version:**
v.3.0.4-beta.24.2

![immagine](https://user-images.githubusercontent.com/38836022/99373546-d3ac0f80-28c1-11eb-8ad1-4bdb0a50a4d4.png)

**Comment by sampoyigi** [comment]
Use issues to report bugs, please start a discussion on the forums or better still search the forums for existing solutions.

**Comment by BreakSecurity** [comment]
But @sampoyigi this is a bug the drop-down should NOT be displayed in this way
