### ISSUE TITLE
"Check of Coupon utilization doesn't work" Case Reappears

### ISSUE THREAD

**Issue by sm2x** [tastyigniter/ti-ext-coupons#7]
TastyIgniter   v3.0.4-beta.25.2
ti-ext-coupons v1.2.0

![image](https://user-images.githubusercontent.com/6595333/102889571-db993980-4495-11eb-9d3c-56b3f4240b4d.png)

**Comment by ryanmitchell** [comment]
Sorry, can you provide more details, its unclear what the issue is.

**Comment by sm2x** [comment]
"Customer Redemptions" is set to just "1" for the same user-customer but it allows accepting more than 1 coupon.

**Comment by ryanmitchell** [comment]
Thanks - I take it the user you are testing with is logged in?

**Comment by sm2x** [comment]
yes indeed, the user is logged in

**Comment by ryanmitchell** [comment]
Can you see if the fix here works for you? 
https://github.com/tastyigniter/ti-ext-coupons/pull/8/commits/fb93ac658fac2874a8e88160c54acb6d261744fd

**Comment by sm2x** [comment]
applied this commit a day before your last post above and seems to fix the issue too for some reason, can you please confirm

![image](https://user-images.githubusercontent.com/6595333/103089732-d79e2080-4629-11eb-85eb-ea9ba2151ed3.png)

**Comment by ryanmitchell** [comment]
Yep it may be the coupon usage wasn’t getting logged - would have been fixed by that commit.

**Comment by sm2x** [comment]
thanks a lot, I will close this issue then
