### ISSUE TITLE
Coupons do NOT get applied on options

### ISSUE THREAD

**Issue by BreakSecurity** [tastyigniter/ti-ext-coupons#9]
**Expected Behaviour**
Once a discount coupon is applied, it should apply to the options as well.
**Actual behaviour**
After applying a discount restricted to only some products, the discount is applied to the menu items but not to any paid options. 

**Reproduce steps**
Create a new coupon that applies a 10% discount to a limited number of items
![immagine](https://user-images.githubusercontent.com/38836022/103417094-a1145880-4b89-11eb-9d74-c81c26dc18f4.png)
![immagine](https://user-images.githubusercontent.com/38836022/103417098-a5d90c80-4b89-11eb-9681-e5c34be70855.png)

Create an order by selecting one or more products to which the coupon can be applied.
As you can see, each product costs 2 euros as a base plus 2 euros as an addition; having selected 6, we are talking about 24 in total
![immagine](https://user-images.githubusercontent.com/38836022/103417113-b4272880-4b89-11eb-8066-e2f52dfd0f4a.png)

By applying the coupon, a discount of 1.20 euros is applied; this is because the discount is applied only on the base price of the product (6 products of 2 euros, i.e. 12), and not on additions (which keep their price unchanged)
Below is an example of how the discount works
![immagine](https://user-images.githubusercontent.com/38836022/103417124-bb4e3680-4b89-11eb-9b65-c29559d9eb54.png)

**Additional informations**
This does not seem to happen instead with discounts that apply to the entire cart without exception
**Version**
v.3.0.4-beta.25.2

**Comment by ryanmitchell** [comment]
@sampoyigi I tried to look into this but cant figure out where the cartItem price is being calculated from...

**Comment by sampoyigi** [comment]
See CartItem::price and CartItem::subtotal

**Comment by ryanmitchell** [comment]
Added a PR here: https://github.com/tastyigniter/flame/pull/26

**Comment by BreakSecurity** [comment]
Thanks @ryanmitchell. Fixed!
